website/website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('websiteapp/', include('websiteapp.urls')),
    path('', RedirectView.as_view(url='/websiteapp/', permanent=True)),
    url(r'^tinymce/', include('tinymce.urls')),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/websiteapp/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^projects/$', views.ProjectListView.as_view(), name='projects'),
    url(r'^projects/(?P<pk>\d+)$', views.ProjectDetailView.as_view(), name='project-detail'),
    url(r'^industry/$', views.IndustryListView.as_view(), name='industry'),
    url(r'^industry/(?P<pk>\d+)$', views.IndustryDetailView.as_view(), name='industry-detail'),
    url(r'^services/$', views.ServiceListView.as_view(), name='services'),
    url(r'^services/(?P<pk>\d+)$', views.ServiceDetailView.as_view(), name='service-detail'),
    url(r'^about-us/$', views.StaffListView.as_view(), name='about-us'),
    url(r'^about-us/(?P<pk>\d+)$', views.StaffDetailView.as_view(), name='staff-detail'),
    #url(r'^contact/$', views.contact, name='contact'),
    url('email/', views.emailView, name='email'),
    url('success/', views.successView, name='success'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

# used like this: <a href="{% url 'index' %}">Home</a> on the template

website/websiteapp/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify

from tinymce.models import HTMLField

from PIL import Image
from .utilities import rescale_image
from django.core.files.uploadedfile import SimpleUploadedFile

from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys

# Create your models here.


# class ProjectDetailContent(models.Model):
#
#    main_title = models.CharField(max_length=100, blank=True, null=True, default='Project')
#    sub_title = models.CharField(max_length=100, blank=True, null=True, default='Project')
#    short_intro = models.TextField(
#        max_length=540, default='We see your project from start to finish.', blank=False, null=False)
#
#    def __str__(self):
#        """
#        String for representing the Service object (in Admin site etc.)
#        """
#        return self.main_title
#

class Industry(models.Model):
    #project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='industries')
    industry = models.CharField(max_length=200, default='')

    class Meta:
        ordering = ["industry"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.industry

    def get_absolute_url(self):
        """
        Returns the url to access a particular project instance.
        """
        return reverse('project-in-industry', args=[str(self.id)])


class Department(models.Model):
    department = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        ordering = ["department"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.department

    def get_absolute_url(self):
        """
        Returns the url to access a particular project instance.
        """
        return reverse('department', args=[str(self.id)])


class Project(models.Model):
    """
    Model representing a project (a specific project).
    """
    title = models.CharField(max_length=200, default='')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)
    client = models.CharField(max_length=200, default='')
    location = models.CharField(max_length=400, blank=True, null=True)
    summary = models.TextField(max_length=400, blank=True, null=True)
    project_article = HTMLField('content', default='')
    industry = models.ForeignKey(Industry,
                                 on_delete=models.CASCADE)

    service = models.ForeignKey('Service',
                                on_delete=models.CASCADE, related_name='type_of_service',  blank=True, null=True)

    #get_industry = Industry.industry.objects.all
    #industry = models.CharField(choices=get_industry, default='construction')
    # imgs = models.ImageField(upload_to='projectimages/mainproject',
    #                         default='serviceimages/None/no-img.jpg')
    project_date = models.DateField(null=True, blank=True)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    class Meta:
        ordering = ["-project_date"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular project instance.
        """
        return reverse('project-detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        #self.slug = '%i-%s' % (self.id, slugify(self.title))
        self.slug = '%s' % (slugify(self.title))
        '''
        self.project_images = [
            self.project_image1,
            self.project_image2,
            self.project_image3,
            self.project_image4,
            self.project_image5,
            self.project_image6
        ]
        # for project_img in project_images_to_resize:
        #    if project_img:
        #        image = project_img
        #        self.project_img = rescale_image(self, image)
        '''
        super(Project, self).save(*args, **kwargs)


class ProjectImage(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='projectimages/gallery/',
                              default='img/home/logo-transparent.png')


class Service(models.Model):
    """
    Model representing each service.
    """

    # Fields
    project = models.ManyToManyField(Project, related_name='services')
    service_title = models.CharField(max_length=100, help_text="Title of service")
    service_article = HTMLField('content')
    service_date = models.DateField(null=True, blank=True)
    service_image1 = models.ImageField(
        upload_to='serviceimages/',
        null=True, blank=True)

    # Metadata

    class Meta:
        ordering = ["service_title"]

    # Methods
    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of service.
        """
        return reverse('service-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Service object (in Admin site etc.)
        """
        return self.service_title

    def save(self, *args, **kwargs):
        if self.service_image1:
            image = self.service_image1
            service_image1 = rescale_image(self, image)
        super(Service, self).save(*args, **kwargs)


class Staff(models.Model):
    """
    Model representing each staff.
    """

    # Fields
    name = models.CharField(max_length=100, help_text="Name of staff")
    position = models.CharField(max_length=100, help_text="Name of Job Position")
    order_of_appearance_on_website = models.IntegerField(
        help_text="Enter Desired Order of appearance on website")
    qualification = models.CharField(max_length=200, help_text="Enter Job Qualification")
    cv = HTMLField('content')
    staff_passport = models.ImageField(
        upload_to='staffimages/', default='staffimages/None/no-img.jpg')
    department = models.ForeignKey(Department,
                                   on_delete=models.CASCADE, blank=True, null=True)

    # Metadata

    class Meta:
        ordering = ["order_of_appearance_on_website"]

    # Methods
    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of staff profile.
        """
        return reverse('staff-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the profile object (in Admin site etc.)
        """
        return self.name


class Home(models.Model):
    """
    A typical class defining a model, derived from the Model class.
    """

    # Fields
    title = models.CharField(max_length=20, help_text="Main Home Title")
    location = models.CharField(max_length=20, help_text="Main Project Location")
    about_us = HTMLField('content')

    # Metadata

    class Meta:
        ordering = ["-title"]

    # Methods
    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of home.
        """
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the home object (in Admin site etc.)
        """
        return self.title


class Press(models.Model):
    """
    Model for Press Releases
    """

    # Fields
    title = models.CharField(max_length=20, help_text="Enter title for press")
    article = HTMLField('content')
    date = models.DateField(null=True, blank=True)
    # Metadata

    class Meta:
        ordering = ["date"]

    # Methods
    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of press.
        """
        return reverse('press-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the press object (in Admin site etc.)
        """
        return self.title

website/websiteapp/forms.py
# make sure this is at the top if it isn't already
from django import forms

# our new form


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

website/websiteapp/views.py
from django.shortcuts import render
from django.views import generic

# send mail with contact form
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.paginator import Paginator
from infinite_scroll_pagination import paginator
from infinite_scroll_pagination import serializers

# using SendGrid's Python Library
# https://github.com/sendgrid/sendgrid-python
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from .models import Project, Press, Staff, Home, Service, Industry, Department

# Create your views here.


def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    projects = Project.objects.all()
    projects = projects[0:4]
    press = Press.objects.all().count()
    # Available books (status = 'a')
    # num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    # num_authors=Author.objects.count()  # The 'all()' is implied by default.

    # Render the HTML template index.html with the data in the context variable

    all_services = Service.objects.all()
    services = all_services[0:4]

    return render(
        request,
        'index.html',
        context={'projects': projects, 'press': press, 'services': services})


class ProjectListView(generic.ListView):
    model = Project
    #model2 = Industry
    paginate_by = 50
    template_name = 'list_page.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        #context['industry_list'] = Industry.objects.all()
        context['service_list2'] = Service.objects.all()

        return context


class ProjectDetailView(generic.DetailView):
    model = Project
    #paginate_by = 1
    template_name = 'detail_page.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        project_service = self.get_object().service
        project_list = Project.objects.filter(
            service__service_title__icontains=project_service)
        paginator = Paginator(project_list, 5)
        page = self.request.GET.get('page')
        context['each_project'] = paginator.get_page(page)
        return context


class ServiceListView(generic.ListView):
    model = Service
    template_name = 'list_page.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['industry_list'] = Industry.objects.all()
        context['project_list2'] = Project.objects.all()
        context['count_civil_projects'] = Project.objects.filter(
            service__service_title__icontains='Civil/')[:4]
        context['count_electrical_projects'] = Project.objects.filter(
            service__service_title__icontains='electrical')[:4]
        context['count_mgt_projects'] = Project.objects.filter(
            service__service_title__icontains='project')[:4]
        context['activate_link'] = 'active'
        return context


class ServiceDetailView(generic.DetailView):
    model = Service
    template_name = 'detail_page.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['industry_list'] = Industry.objects.all()
        context['project_list2'] = Project.objects.all()
        context['count_civil_projects'] = Project.objects.filter(
            service__service_title__icontains='Civil/')
        context['count_electrical_projects'] = Project.objects.filter(
            service__service_title__icontains='electrical')
        context['count_mgt_projects'] = Project.objects.filter(
            service__service_title__icontains='project')
        context['activate_link'] = 'active'
        return context


class IndustryDetailView(generic.DetailView):
    model = Industry
    template_name = 'detail_page.html'


class IndustryListView(generic.ListView):
    model = Industry
    template_name = 'list_page.html'


class StaffListView(generic.ListView):
    model = Staff
    paginate_by = 10
    #template_name = 'list_page.html'

    def get_context_data(self, **kwargs):
        context = super(StaffListView, self).get_context_data(**kwargs)
        all_services = Service.objects.all()
        context['services'] = all_services[0:3]
        context['departments'] = Department.objects.all()
        return context


class StaffDetailView(generic.DetailView):
    model = Staff


def emailView(request):
    print('This is the request: ')
    print(request)
    if request.method == 'GET':
        form = request.POST
    else:
        form = request.POST
        if form:
            subject = form['subject']
            from_email = form['from_email']
            message = form['message']
            try:
                #sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
                send_mail(subject, message, from_email,
                          ['admin@projectpluspotentials.com'])
                print('###I got here')
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('success')
    return render(request, "email.html", {'form': form})


def successView(request):
    return render(request, 'success.html')

website/websiteapp/templates/email.html
<h1>Contact Us</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
</form>

website/websiteapp/templates/list_page.html
{% extends "base_generic.html" %}

{% load static%}

{% block page_title %}<title>{% if project_list %} Projects{% else %} Services{% endif %} | {{block.super}} </title>{% endblock %}
{% block meta_description %}
<meta name="description" content="
Our vision is to produce independent, high-class engineers in our field of
engineering as well as world-class engineering services in our
core area of services."/>
{% endblock %}

{% load websiteapp_extras %}
{% load mycounter %}

{% block carousel %}
<div class="main-image"
    {% if project_list %}style="background-image:url({%static '/img/warehouse.jpeg'%});"{% endif %}
    {% if service_list %}style="background-image:url({%static '/img/IKOYI-3.jpg'%});"{% endif %}
    >
    <div class="carousel-caption">
        <span class="animated bounce"></span>
        <div class="box animated fadeIn" style="animation-delay: 1s">
            <h2 class="animated bounceInRight" style="animation-delay: 1s">
                {% if project_list %}Projects {%endif%}
                {% if service_list %}Our Services {%endif%}
            </h2>
        </div>

    </div>
</div>
{% endblock %}

{% load django_bootstrap_breadcrumbs %}
<div class='breadcrumbs'>
{% block breadcrumbs %}
    {{ block.super }}
    {% if project_list %}{% breadcrumb "Projects" "projects" %} {% endif %}
    {% if service_list %}{% breadcrumb "Services" "services" %} {% endif %}
{% endblock %}
{% block conten %}
    {% render_breadcrumbs %}
{% endblock %}
</div>


{% block content %}





<section class="description">
    <div class="container" >
        <div class="row">

            {% if project_list %}
            <div class="" style="padding-left:10px; width: 100%">
              <h1 class="mb-3">You Dream it. We Design and Execute.</h1>
              <p>
                  Your projects are our pride. Every project is designed with
                   <strong>Broad Vision</strong> that meets clients requirement,
                   covering the edge cases; <strong>Careful Thought</strong> from experienced
                   enginners and trusted partners, and <strong>Computer Aided Designs</strong>
                   for state-of-the-art project designs and execution. We suggest the best ideas
                   and develop them - always communicating with clients to ensure project is
                   completed on time and on budget.
              </p>
              <div class="row">
                <div class="col">
                  <p class="mb-1">Filters:</p>
                </div>
              </div>
              <div class="row mb-3">
                <div class="col">
                  <div class="btn-group-sm btn-group-toggle" data-toggle="buttons">
                      <label class="btn btn-outline-primary active">
                        <input type="radio" name="shuffle-filter" value="all" checked="checked"/>All
                      </label>
                     {% for service in service_list2 %}
                     <label class="btn btn-outline-primary">
                       <input type="radio" name="shuffle-filter" value="{{service}}"/>{{service}}
                     </label>
                     {% endfor %}
                  </div>
                </div>
              </div>
              <div class="row my-shuffle infinite-container">
                  {% for project in project_list %}

                <figure class="infinite-item image-item col-sm-3" data-groups='["{{project.service}}"]' >
                    <a href="{% url 'project-detail' project.id %}"  >
                  <div class="aspect aspect--16x9">

                    <div class="aspect__inner" data-bs-hover-animate="pulse" data-aos="fade-right">
                        {% if project.projectimage_set.all.first.image %}
                        <img class="img-fluid" src="{{project.projectimage_set.all.first.image.url}}" obj.alt="obj.alt"/>
                        {% else %}
                        <img class="img-fluid" src="{% static '/img/home/logo-transparent.png' %}"/>
                        {% endif %}
                    </div>

                  </div>
                  <figcaption data-bs-hover-animate="pulse">
                      <small>
                          <strong>{{project.title | truncatechars:33}}</strong><br />
                         <em>{{project.summary | truncatechars:60}}</em>
                      </small>
                  </figcaption>
                  </a>
                </figure>
                {% endfor %}
                </div>
            </div>
            {% endif %}

            {% if service_list %}
            <div class='accordion'>
                <h2 class="mb-3">We are 100% Committed to Offering Quality Service.</h2>
                <p>
                    Our service offerings are:
                    <ul>
                        {% for service in service_list %}
                        <li>
                            {{service}}
                        </li>
                        {% endfor %}
                    </ul>
                </p>
                {% for service in service_list %}
                    {% with "#"|addstr:service as targetid %}
                        <button data-toggle="collapse" data-parent="#accordion" data-target={{targetid}} style="width:100%">
                            <h4 class='service-title'>
                                <strong>{{service}}</strong>
                            </h4>
                            <small class='text-center' {% if forloop.first %} style="display:none" {% else %}style="display:block"{% endif %}>
                            <a href=""></a>Click here to see recent {{service}} projects
                            </small>
                        </button>
            <div {% if forloop.first %} class="panel-collapse in" {% else %} class="panel-collapse collapse" {% endif %} id={{targetid|slice:"1:"}} data-aos="fade-right">
                {% endwith %}
                <a href='{% url 'service-detail' service.id %}'><small class='text-center'><strong>Click here to see ALL {{service}} projects</strong></small></a>

                <div class="row projects" style="margin: 15px auto">
                    {% if count_civil_projects %}
                        {% for project in count_civil_projects|slice:':4' %}
                            {% if project.service == service%}
                                        <div class="col-md-12 col-lg-5" style="height: 224.5px; max-width: 300px; padding:0; margin:0; border-style:solid; border-color: #deae64e6; border-width: 5px; ">
                                            <a href="{% url 'project-detail' project.id %}" >
                                                <img class="img-fluid" style='max-height:215px; width: 100%; object-fit: contain'
                                                {% if project.projectimage_set.all.first.image %}
                                                src="{{project.projectimage_set.all.first.image.url}}"
                                                {% else %}
                                                src="{% static '/img/home/logo-transparent.png' %}"
                                                {% endif %}/>
                                            </a>
                                        </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}


                    {% if count_electrical_projects %}
                        {% for project in count_electrical_projects|slice:':4' %}
                            {% if project.service == service%}
                                        <div class="col-md-12 col-lg-5" style="height: 224.5px; max-width: 300px; padding:0; margin:0; border-style:solid; border-color: #deae64e6; border-width: 5px; ">
                                            <a href="{% url 'project-detail' project.id %}" >
                                                <img class="img-fluid" style='max-height:215px; width: 100%; object-fit: contain'
                                                {% if project.projectimage_set.all.first.image %}
                                                src="{{project.projectimage_set.all.first.image.url}}"
                                                {% else %}
                                                src="{% static '/img/home/logo-transparent.png' %}"
                                                {% endif %}/>
                                            </a>
                                        </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    {% if count_mgt_projects %}
                        {% for project in count_mgt_projects|slice:':4' %}
                            {% if project.service == service%}
                                        <div class="col-md-12 col-lg-5" style="height: 224.5px; max-width: 300px; padding:0; margin:0; border-style:solid; border-color: #deae64e6; border-width: 5px; ">
                                            <a href="{% url 'project-detail' project.id %}" >
                                                <img class="img-fluid" style='max-height:215px; width: 100%; object-fit: contain'
                                                {% if project.projectimage_set.all.first.image %}
                                                src="{{project.projectimage_set.all.first.image.url}}"
                                                {% else %}
                                                src="{% static '/img/home/logo-transparent.png' %}"
                                                {% endif %}/>
                                            </a>
                                        </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}


                        <div class="service-projects" style="">
                            <h6><strong>{{service}}</strong></h6>
                            <small>
                            <ul>
                            {% for project in count_civil_projects|slice:':4' %}
                                {% if project.service == service %}

                                <li>
                                    <a><strong> {{project.title}}: </strong>{{project.summary| truncatechars:120}}</a>
                                </li>

                            {% endif %}
                            {% endfor %}

                            {% for project in count_electrical_projects|slice:':4' %}
                                {% if project.service == service %}

                                <li>
                                    <a><strong> {{project.title}}:</strong>{{project.summary}}</a>
                                </li>

                            {% endif %}
                            {% endfor %}

                            {% for project in count_mgt_projects|slice:':4' %}
                                {% if project.service == service %}

                                <li>
                                    <a><strong> {{project.title}}:</strong>{{project.summary}}</a>
                                </li>

                            {% endif %}
                            {% endfor %}
                            </ul>
                            </small>
                        </div>
            </div>

            </div>



            {% endfor %}

            </div>

            {% endif %}
    </div>
        </div>
    </div>
</section>
<!--
    <h1>Project List</h1>
    {% if project_list %}
    <ul>
      {% for project in project_list %}
      <li>
        <a href="{{ project.get_absolute_url }}">{{ project.title }}</a> ({{project.client}})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no projects right now.</p>
    {% endif %}
-->



{% endblock %}

website/websiteapp/templates/lit_page.html
{% extends "base_generic.html" %}

{% load static%}
{% load websiteapp_extras %}

{% block carousel %}
<div class="main-image"
    {% if project_list %}style="background-image:url({%static '/img/warehouse.jpeg'%});"{% endif %}
    {% if service_list %}style="background-image:url({%static '/img/IKOYI-3.jpg'%});"{% endif %}
    >
    <div class="carousel-caption">
        <span class="animated bounce"></span>
        <div class="box animated fadeIn" style="animation-delay: 1s">
            <h2 class="animated bounceInRight" style="animation-delay: 1s">
                {% if project_list %}Projects {%endif%}
                {% if service_list %}Our Services {%endif%}
            </h2>
        </div>

    </div>
</div>
{% endblock %}

{% load django_bootstrap_breadcrumbs %}
<div class='breadcrumbs'>
{% block breadcrumbs %}
    {{ block.super }}
    {% if project_list %}{% breadcrumb "Projects" "projects" %} {% endif %}
    {% if service_list %}{% breadcrumb "Services" "services" %} {% endif %}
{% endblock %}
{% block conten %}
    {% render_breadcrumbs %}
{% endblock %}
</div>


{% block content %}

<section style="background-color: #e9ecef;">


<div class="container">
  <h1 class="mb-3">You Dream it. We Design and Execute.</h1>
  <p>
      Your projects are our pride. Every project is designed with
       <strong>Broad Vision</strong> that meets clients requirement,
       covering the edge cases; <strong>Careful Thought</strong> from experienced
       enginners and trusted partners, and <strong>Computer Aided Designs</strong>
       for state-of-the-art project designs and execution. We suggest the best ideas
       and develop them - always communicating with clients to ensure project is
       completed on time and on budget.
  </p>
  <div class="row">
    <div class="col">
      <p class="mb-1">Filters:</p>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col">
      <div class="btn-group btn-group-toggle" data-toggle="buttons">
          <label class="btn btn-outline-primary active">
            <input type="radio" name="shuffle-filter" value="all" checked="checked"/>All
          </label>
         {% for service in service_list2 %}
         <label class="btn btn-outline-primary">
           <input type="radio" name="shuffle-filter" value="{{service}}"/>{{service}}
         </label>
         {% endfor %}
      </div>
    </div>
  </div>
  <div class="row my-shuffle">
      {% for project in project_list %}

    <figure class="image-item col-3" data-groups='["{{project.service}}"]'>
        <a href="{% url 'project-detail' project.id %}"  >
      <div class="aspect aspect--16x9">

        <div class="aspect__inner" data-bs-hover-animate="pulse" data-aos="fade-right">

            <img src="{{project.projectimage_set.all.first.image.url}}" obj.alt="obj.alt"/>
        </div>

      </div>
      <figcaption data-bs-hover-animate="pulse">
          <small>
              <strong>{{project.title}}</strong><br />
             <em>{{project.summary}}</em>
          </small>
      </figcaption>
      </a>
    </figure>

    {% endfor %}
    </div>
</div>

</section>
{% endblock %}

website/websiteapp/templates/success.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

<p>
    Thank for Contacting Us. We will get back to you shortly.
</p>


{% endblock %}